package com.myspace.test_hook;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class emp implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer empid;

	public emp() {
	    
	}

	public java.lang.Integer getEmpid() {
		return this.empid;
	}

	public void setEmpid(java.lang.Integer empid) {
		this.empid = empid; 
	}

	public emp(java.lang.Integer empid) {
		this.empid = empid;
	}

}