package com.myspace.test_hook;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class emp implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public emp() {
    }




}